import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {WebSocketServer} from 'ws';
const ROOT=path.join(path.dirname(fileURLToPath(import.meta.url)),'..','public'),PORT=Number(process.env.PORT||10000),MAX=16,MIN=2,TICK=20;const rooms=new Map();
const permanentCodes=Array.from({length:10},(_,i)=>`LUMI-${String(i+1).padStart(2,'0')}`);const colors=['#74d7ff','#ff8ab7','#b7ff79','#c8a7ff','#ffd166','#7fffd4','#ff9f68','#9db7ff'];const spawns=[{x:500,y:500},{x:760,y:500},{x:1020,y:500},{x:1280,y:500},{x:500,y:760},{x:760,y:760},{x:1020,y:760},{x:1280,y:760}];
function uid(){return Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-4)}function code(){return 'L-'+Math.random().toString(36).slice(2,7).toUpperCase()}function safe(v){return String(v||'Lumi').replace(/[<>]/g,'').trim().slice(0,18)||'Lumi'}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
class Room{constructor(c,n,permanent=false,isPrivate=false){this.code=c;this.name=n;this.permanent=permanent;this.private=isPrivate;this.players=new Map();this.hostId=null;this.started=false;this.phase=0;this.objective={need:3,got:0,label:'Restore the first Memory Beacon'};this.beacons=[{x:820,y:900,active:false},{x:1600,y:620,active:false},{x:2380,y:1320,active:false}];this.shards=new Set();this.waitStartedAt=0;this.extensionStartedAt=0;this.lastActivity=Date.now()}
 add(p){if(!this.hostId)this.hostId=p.id;this.players.set(p.id,p);this.lastActivity=Date.now();if(this.permanent&&!this.waitStartedAt)this.waitStartedAt=Date.now()}
 remove(id){this.players.delete(id);if(this.hostId===id)this.hostId=this.players.values().next().value?.id||null;this.lastActivity=Date.now()}
 snapshot(){return [...this.players.values()].map(p=>({id:p.id,name:p.name,x:p.x,y:p.y,color:p.color,face:p.face,typing:p.typing}))}
 state(){return {protocol:4,code:this.code,name:this.name,permanent:this.permanent,private:this.private,started:this.started,phase:this.phase,objective:this.objective,players:this.snapshot(),count:this.players.size,max:MAX,minPlayers:MIN,hostId:this.hostId,beacons:this.beacons,waitStartedAt:this.waitStartedAt,extensionStartedAt:this.extensionStartedAt}}
 send(o,except){const s=JSON.stringify(o);for(const p of this.players.values())if(p.id!==except&&p.ws.readyState===1)p.ws.send(s)}
 broadcast(o){this.send(o)}
 start(){if(this.started||this.players.size<MIN)return false;this.started=true;this.send({type:'match-start',room:this.state()});this.send({type:'room-state',room:this.state()});return true}
 collect(p){if(!this.started)return;if(this.shards.size>=this.objective.need)return;const key=`${Math.floor(p.x/100)}:${Math.floor(p.y/100)}`;if(this.shards.has(key))return;this.shards.add(key);this.objective.got++;this.send({type:'shard',got:this.objective.got,need:this.objective.need,by:p.name,x:p.x,y:p.y});if(this.objective.got>=this.objective.need){this.phase++;const labels=['Restore the next Memory Beacon','Wake the sleeping district','Open the hidden garden','Discover the final memory'];this.objective={need:3+this.phase,got:0,label:labels[Math.min(this.phase,labels.length-1)]};this.shards.clear();if(this.beacons[this.phase-1])this.beacons[this.phase-1].active=true;this.send({type:'world-change',phase:this.phase,objective:this.objective,beacons:this.beacons});this.send({type:'room-state',room:this.state()})}}
 tick(){if(!this.started&&this.permanent&&this.players.size){if(this.players.size>=MIN)this.start();else if(!this.extensionStartedAt&&Date.now()-this.waitStartedAt>=300000){this.extensionStartedAt=Date.now();this.send({type:'room-state',room:this.state(),timerPhase:'extension'})}else if(this.extensionStartedAt&&Date.now()-this.extensionStartedAt>=180000)this.start()}if(this.started){for(const p of this.players.values()){if(!p.input)continue;let dx=(p.input.r?1:0)-(p.input.l?1:0),dy=(p.input.d?1:0)-(p.input.u?1:0);if(dx&&dy){dx*=.7071;dy*=.7071}const speed=230/TICK;p.x=clamp(p.x+dx*speed,80,3120);p.y=clamp(p.y+dy*speed,80,2020);if(dx||dy)p.face=Math.atan2(dy,dx)}if(Math.random()<0.035){const arr=[...this.players.values()];if(arr.length)this.collect(arr[Math.floor(Math.random()*arr.length)])}this.send({type:'snapshot',roomCode:this.code,players:this.snapshot(),phase:this.phase,objective:this.objective})}}
}
for(let i=0;i<10;i++)rooms.set(permanentCodes[i],new Room(permanentCodes[i],`LUMI DISTRICT ${i+1}`,true,false));
function list(){return [...rooms.values()].filter(r=>!r.private).map(r=>({code:r.code,name:r.name,count:r.players.size,max:MAX,permanent:r.permanent,started:r.started,phase:r.phase}))}
const server=http.createServer((req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);if(u.pathname==='/health'){res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({ok:true,rooms:rooms.size}));return}if(u.pathname==='/api/rooms'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(list()));return}let f=path.join(ROOT,u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname));if(!f.startsWith(ROOT)){res.writeHead(403);return res.end()}fs.readFile(f,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':({'.html':'text/html','.js':'text/javascript','.css':'text/css'})[path.extname(f)]||'application/octet-stream','cache-control':'no-store'});res.end(d)})});
const wss=new WebSocketServer({server});wss.on('connection',(ws,req)=>{const u=new URL(req.url,`http://${req.headers.host}`);let rc=(u.searchParams.get('room')||'').toUpperCase(),room=rc?rooms.get(rc):null;if(rc==='CREATE'){room=new Room(code(),safe(u.searchParams.get('name')),false,u.searchParams.get('private')==='1');rooms.set(room.code,room)}if(!room){ws.send(JSON.stringify({type:'error',message:'Room not found'}));ws.close();return}if(room.players.size>=MAX){ws.send(JSON.stringify({type:'error',message:'Room is full'}));ws.close();return}const id=uid(),sp=spawns[room.players.size%spawns.length],p={id,name:safe(u.searchParams.get('name')),color:colors[room.players.size%colors.length],x:sp.x,y:sp.y,face:0,typing:false,input:{},ws};room.add(p);ws._room=room.code;ws._player=id;ws.send(JSON.stringify({type:'welcome',protocol:4,id,room:room.state(),world:{w:3200,h:2100}}));room.send({type:'player-joined',player:{id:p.id,name:p.name,color:p.color,x:p.x,y:p.y}} ,id);room.send({type:'room-state',room:room.state()});ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}if(m.type==='input')p.input={u:!!m.u,d:!!m.d,l:!!m.l,r:!!m.r};else if(m.type==='chat'){const t=String(m.text||'').replace(/[<>]/g,'').trim().slice(0,160);if(t)room.send({type:'chat',from:p.name,color:p.color,text:t})}else if(m.type==='start')room.start()});ws.on('close',()=>{if(ws._closed)return;ws._closed=true;if(room.players.has(id)){room.remove(id);room.send({type:'player-left',id});room.send({type:'room-state',room:room.state()})}})});setInterval(()=>{for(const [k,r] of rooms){r.tick();if(!r.permanent&&!r.players.size&&Date.now()-r.lastActivity>600000)rooms.delete(k)}},1000/TICK);server.listen(PORT,'0.0.0.0',()=>console.log('LUMI 2.2 listening',PORT));
